#!/bin/bash

echo "Checking commit message format..."

# The first arg is the path to the git commit temporary file
TEMPORARY_FILE_PATH=$1

# Get commit-message from the temporary file
COMMIT_MSG=`head -n1 $TEMPORARY_FILE_PATH`

REGEX="^(feat|fix|perf|docs|style|refactor|test|build|merge|hotfix): .+$"

# Check if the commit message matches the regex pattern
if [[ ! $COMMIT_MSG =~ $REGEX ]]; then
  echo "Invalid commit message format"
  echo "Usage: <prefix>: message"
  echo "Available prefixes: feat, fix, perf, docs, style, refactor, test, build"
  exit 1
fi

echo "Commit message format is valid."
exit 0
