version: '3.3'
services:
  api1:
    container_name: "runner-api"
    build:
      context: ${RUNNER_PROJECT_PATH}
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    expose:
      - 8080

  api2:
    container_name: "permissions-api"
    build:
      context: ${PERMISSIONS_PROJECT_PATH}
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      DB_HOST: postgres
      DB_PORT: 5432
    env_file:
      - .env
    depends_on:
      - postgres
    expose:
      - 8081

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env

  api3:
    container_name: "operations-api"
    build:
      context: ${OPERATIONS_PROJECT_PATH}
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    expose:
      - 8082

volumes:
  postgres-data:
