services:
  api1:
    container_name: "snippet_searcher_runner"
    image: ghcr.io/ingsis-group-12/snippet-searcher-runner:main
    ports:
      - "8080:8080"

  api2.1:
    container_name: "snippet_operations"
    image: ghcr.io/ingsis-group-12/snippet-operations:main
    ports:
      - "8081:8081"
    depends_on:
      - api2.2

  api2.2:
    container_name: "asset_service"
    image: ghcr.io/austral-ingsis/snippet-asset-service:latest
    ports:
      - "8082:8082"
    environment:
      AZURE_HOST: "http://azurite"

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: "azurite"
    hostname: azurite
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - blob:/workspace

  api3:
    container_name: "snippet_permissions"
    image: ghcr.io/ingsis-group-12/snippet-permissions:main
    ports:
      - "8083:8083"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env

  printscript-ui:
    container_name: "printscript_ui"
    image: ghcr.io/ingsis-group-12/printscript-ui:master
    ports:
      - "5173:5173"
    environment:
      VITE_FRONTEND_URL: ${VITE_FRONTEND_URL}
      VITE_BACKEND_URL: ${VITE_BACKEND_URL}
      VITE_REACT_APP_AUTH0_DOMAIN: ${VITE_REACT_APP_AUTH0_DOMAIN}
      VITE_REACT_APP_AUTH0_CLIENT_ID: ${VITE_REACT_APP_AUTH0_CLIENT_ID}
      VITE_REACT_APP_AUTH0_AUDIENCE: ${VITE_REACT_APP_AUTH0_AUDIENCE}
      VITE_REACT_APP_AUTH0_CALLBACK_URL: ${VITE_REACT_APP_AUTH0_CALLBACK_URL}
    env_file:
      - .env

volumes:
  postgres-data:
  blob:
    external: false
