services:
  api_runner:
    container_name: "snippet_searcher_runner"
    image: ghcr.io/ingsis-group-12/snippet-searcher-runner:main
    restart: always
    ports:
      - "8080:8080"

  api_operations:
    container_name: "snippet-operations"
    image: ghcr.io/ingsis-group-12/snippet-operations:main
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_OPERATIONS_HOST}
      BUCKET_URL: ${BUCKET_URL}
      POSTGRES_OPERATIONS_PORT: ${POSTGRES_OPERATIONS_PORT}
      PERMISSIONS_URL: ${PERMISSIONS_URL}
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - api_asset
      - postgres_operations

  api_asset:
    container_name: "asset_service"
    image: ghcr.io/austral-ingsis/snippet-asset-service:latest
    restart: always
    ports:
      - "8082:8080"
    environment:
      AZURE_HOST: "http://azurite"
      NEW_RELIC_AGENT_ENABLED: false

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: "azurite"
    hostname: azurite
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - blob:/workspace

  api_permissions:
    container_name: "snippet-permissions"
    image: ghcr.io/ingsis-group-12/snippet-permissions:main
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PERMISSIONS_HOST: ${POSTGRES_PERMISSIONS_HOST}
      POSTGRES_PERMISSIONS_PORT: ${POSTGRES_PERMISSIONS_PORT}
    ports:
      - "8083:8083"
    depends_on:
      - postgres_permissions

  postgres_operations:
    container_name: "operations-db"
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-operations-data:/var/lib/postgresql/data
    restart: always

  postgres_permissions:
    container_name: "permissions-db"
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres-permissions-data:/var/lib/postgresql/data
    restart: always

  printscript-ui:
    container_name: "printscript-ui"
    image: ghcr.io/ingsis-group-12/printscript-ui:master
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - dist-volume:/app/dist

  reverse-proxy:
    container_name: "reverse-proxy"
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
      - ./nginx/images/:/usr/share/nginx/images/:ro
      - dist-volume:/usr/share/nginx/dist

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    restart: always

volumes:
  postgres-operations-data:
  postgres-permissions-data:
  blob:
    external: false
  dist-volume:
