name: Update repo and deploy [ dev VM ]

on:
  push:
    branches: [ "dev" ]

jobs:
  update-repo-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_DEV_HOST }}
          username: ${{ secrets.VM_DEV_USER }}
          key: ${{ secrets.VM_DEV_SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /app/snippet-infrastructure
            sudo git checkout dev
            sudo git pull
            sudo docker compose --profile full-setup pull
            sudo docker compose --profile full-setup up -d
